var dataAry = [
	{
		desc:'原型為美國二戰中最著名的驅逐艦弗萊徹，名字來源於一戰時的海軍上將法蘭克•弗萊德•弗萊徹(Frank Friday Fletcher），作為二戰著名的餃子王級驅逐艦的首艦（儘管不是第一個下水的）陽炎號說她家姐妹多，一個電話能叫來18個妹妹，弗萊徹笑哭了（弗萊徹的妹妹有174個）。',
		name:'弗莱彻',
		hangji:'驱逐',
		shengyou:'村川梨衣',
		audios:'audio/fulai/Fletcher_01.wav',
		bg:'fulai.jpg'
	},
	{
		desc:'原型為舊日本海軍第二航空戰隊所屬中型正規航母「飛龍（ひりゅう）」，動畫裡二航戰出場次數不多，基本都是一航戰的陪襯背景，後來蒼龍一起隨第一機動部隊攻略MI。',
		name:'飞龙',
		hangji:'航母',
		shengyou:'福井裕佳梨',
		audios:'audio/feilong/Hiryu_01.wav',
		bg:'feilong.jpg'
	},
	{
		desc:'原型為1930年1月法國海軍「空想」戰艦，該級艦除了航速快以外，更裝備有極強的武備，並且擁有一個低矮的側影，因此該級艦無疑可擠身於世界最強驅逐艦之列。在動漫中是一位喜歡像風一樣奔跑的少女，對於自由自在奔跑的感覺的追求比起什麼都重要',
		name:'空想',
		hangji:'驱逐',
		shengyou:'村川梨衣',
		audios:'audio/kongxiang/LeFantasque_01.wav',
		bg:'kongxiang.jpg'
	},
	{
		desc:'原型為皇家方舟號航空母艦是英國皇家海軍在第二次世界大戰前全新的設計的航空母艦，開創了現代航空母艦的新紀元。禦姐外型的皇家方舟究竟會在漫畫中有何表現？我們一起期待吧！',
		name:'皇家方舟',
		hangji:'航母',
		shengyou:'佐藤莉奈',
		audios:'audio/huangjia/ArkRoyal_01.wav',
		bg:'huangjia.jpg'
	},
	{
		desc:'原型為厭戰號戰列艦（HMS Warspite）是英國皇家海軍的一艘伊莉莎白女王級戰列艦。至今仍是皇家海軍最負盛名的艦隻之一。由於歷史上一句「毫無疑問，當這位可敬的老女士提起裙子時，她還是能跑的。」，厭戰從此被提督戲稱為「老太太」',
		name:'厌战',
		hangji:'战列',
		shengyou:'福井裕佳梨',
		audios:'audio/yanzhan/Warspite_01.wav',
		bg:'yanzhan.jpg'
	}
];